def plane():
    print("************************************************************************************")
    print("                             AVAILABLE FLIGHTS                                  ")
    print("************************************************************************************")
    print(" Serial Number   Flight Number    From       Destination      Time      Cost    ")
    print("     1              IND-108      Mumbai        Rome         11:00PM     100$    ")
    print("     2              IND-320     Hyderabad      Dubai        01:00AM     250$    ")
    print("     3              IND-170       Delhi        Tokyo        03:00AM     150$    ")
    print("     4              IND-102      Chennai       Paris        02:00AM     500$    ")
    print("     5              IND-101      Kolkata      New York      09:00AM     400$    ")